$HTTP["useragent"] =~ "[Bb]ot|[Gg]oogle" {
	$HTTP["url"] =~ "^/giftbot/deref.fcgi" {
		url.access-deny = ( "" )
	}
}

$HTTP["url"] =~ "^/?" {
	dir-listing.activate = "enable"
	mimetype.assign = (
		".tcl" => "text/plain; charset=utf-8",
		".sh" => "text/plain; charset=utf-8",
		"" => "text/plain; charset=utf-8"
	)
}

fastcgi.server += (
	"weblinksuche.fcgi" => ((
		"bin-path" => "/data/project/giftbot/public_html/weblinksuche.fcgi",
		"bin-environment" => ( "LC_ALL" => "en_US.UTF-8" ),
		"socket" => "/tmp/tcl.socket.giftbot.weblinksuche"
	))
)

fastcgi.server += (
	"deref.fcgi" => ((
		"bin-path" => "/data/project/giftbot/public_html/deref.fcgi",
		"bin-environment" => ( "LC_ALL" => "en_US.UTF-8" ),
		"socket" => "/tmp/tcl.socket.giftbot.deref"
	))
)

fastcgi.server += (
	"parsetemplates-getcsv.fcgi" => ((
		"bin-path" => "/data/project/giftbot/public_html/parsetemplates-getcsv.fcgi",
		"bin-environment" => ( "LC_ALL" => "en_US.UTF-8" ),
		"socket" => "/tmp/tcl.socket.giftbot.parsetemplates-getcsv"
	))
)
